# Generated by Django 5.1.4 on 2025-01-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumePy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(default='files/default.pdf', upload_to='files'),
            preserve_default=False,
        ),
    ]
