# Generated by Django 5.1.4 on 2025-01-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumePy', '0003_alter_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(default='def@mail.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(max_length=1000, upload_to='static/files'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(default='default name', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(default='9999999', max_length=100),
        ),
    ]
