# Generated by Django 5.1.4 on 2025-01-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumePy', '0004_alter_resume_email_alter_resume_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(max_length=1000, upload_to='resumes/'),
        ),
    ]
