# Generated by Django 5.1.4 on 2025-01-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumePy', '0005_alter_resume_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='email',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone',
        ),
    ]
