# Generated by Django 5.1.4 on 2025-01-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumePy', '0006_remove_resume_email_remove_resume_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(default='def@mail.com', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='default name', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(default='9999999', max_length=100),
        ),
    ]
