# Generated by Django 5.1.4 on 2025-01-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumePy', '0007_resume_email_resume_name_resume_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='Candidate',
        ),
    ]
